services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tvscheduler
      MYSQL_USER: user
      MYSQL_PASSWORD: securepassword
    ports:
      - "6666:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    build:
      context: ../
      dockerfile: tvscheduler/Dockerfile
    container_name: tvscheduler-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5171:8080"
    depends_on:
      - mariadb

  frontend:
    build:
      context: ../tvscheduler-react-app/tvscheduler-react-app
    container_name: tvscheduler-frontend
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  mariadb_data: